### PR TITLE
Added UWP support

### PR DESCRIPTION
**Pull request by gentledepp**
This is a first UWP support tryout.

Please do not merge yet as I did not even have the time to trest it in an UWP app!

I send you the PR mainly to prevent somebody else going the long way just like me.

Also one missing feature is:
Calling "GetImage" specifying a different Stroke and Fill color will not work. Those parameters will simply be ingored by now.

### CODE REVIEW

**Comment by charlesroddie** [comment]
Have you tested this yet?

**Comment by gentledepp** [comment]
Nope - Actually I already forgot that I did this :)
But we are about to add UWP support in the next two weeks so I may be able to give you an answer ;-)

**Comment by charlesroddie** [comment]
Great!

**Comment by maxim-tkachenko** [comment]
[here](https://github.com/maxim-tkachenko/XamarinSignaturePad/tree/uwp) is another version of uwp support. still need to add implementation for getting/loading a list of points, but it already works

**Pull request closed without merging**
